import React, { useState } from 'react';
import { Building2, ChevronDown, Plus, Check } from 'lucide-react';
import { useFoodSystem } from '../context/FoodSystemContext';
export const RestaurantSwitcher: React.FC = () => {
  const { restaurants, activeRestaurant, selectRestaurant, createRestaurant } = useFoodSystem();
  const [open, setOpen] = useState(false); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [city, setCity] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); createRestaurant(name, city); setName(''); setCity(''); setCreating(false); setOpen(false); };
  return <div className="relative"><button onClick={() => setOpen(value => !value)} className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-900/90 px-3 py-2 text-left hover:border-orange-500/60"><Building2 className="h-4 w-4 text-orange-400" /><span className="max-w-[150px]"><span className="block text-[9px] uppercase text-slate-500">Restaurante ativo</span><span className="block truncate text-xs font-extrabold text-white">{activeRestaurant.name}</span></span><ChevronDown className="h-3.5 w-3.5 text-slate-400" /></button>{open && <div className="absolute left-0 top-full z-50 mt-2 w-72 rounded-2xl border border-slate-700 bg-[#121929] p-2 shadow-2xl"><div className="px-2 py-1 text-[10px] font-black uppercase text-slate-500">Minhas unidades</div>{restaurants.map(restaurant => <button key={restaurant.id} onClick={() => { selectRestaurant(restaurant.id); setOpen(false); }} className="flex w-full items-center gap-2 rounded-xl px-2 py-2 text-left hover:bg-slate-800"><Building2 className="h-4 w-4 text-orange-400" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-white">{restaurant.name}</span><span className="block text-[10px] text-slate-500">{restaurant.city || 'Cidade não informada'}</span></span>{restaurant.id === activeRestaurant.id && <Check className="h-4 w-4 text-emerald-400" />}</button>)}<div className="my-2 border-t border-slate-800" />{creating ? <form onSubmit={submit} className="space-y-2 p-1"><input autoFocus required value={name} onChange={event => setName(event.target.value)} placeholder="Nome do restaurante" className="w-full rounded-lg border border-slate-700 bg-slate-950 px-2.5 py-2 text-xs text-white" /><input value={city} onChange={event => setCity(event.target.value)} placeholder="Cidade (opcional)" className="w-full rounded-lg border border-slate-700 bg-slate-950 px-2.5 py-2 text-xs text-white" /><div className="flex gap-2"><button type="button" onClick={() => setCreating(false)} className="flex-1 rounded-lg bg-slate-800 py-2 text-[11px] font-bold text-slate-300">Cancelar</button><button type="submit" className="flex-1 rounded-lg bg-orange-500 py-2 text-[11px] font-bold text-white">Criar</button></div></form> : <button onClick={() => setCreating(true)} className="flex w-full items-center gap-2 rounded-xl px-2 py-2 text-xs font-bold text-orange-400 hover:bg-orange-500/10"><Plus className="h-4 w-4" /> Adicionar restaurante</button>}</div>}</div>;
};
